# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Razvezu.xcodeproj")
    match(type: "appstore")
    build_app(workspace: "Razvezu.xcworkspace", scheme: "Razvezu")
    upload_to_testflight(skip_submission: true)
  end
end
